name: VanRiperMktg
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.91068
title: '(n). noun: fortunate ramblings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#150505'
    - '#9b5521'
    - '#c2b6ba'
    - '#5d577b'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
