name: VanRiperMktg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35309
title: Van Riper Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff3f6'
    - '#c5d4e2'
    - '#0b0a06'
    - '#414751'
    - '#928b86'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
