name: VanRiperMktg
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.91068
title: '(n). noun: fortunate ramblings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfff8'
    - '#232122'
    - '#bdaea7'
    - '#9c131b'
    - '#7cf1fd'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
