name: VanRiperMktg
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.40651
title: '(n). noun: fortunate ramblings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfff8'
    - '#232122'
    - '#bdaea7'
    - '#9c131b'
    - '#7cf1fd'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
