name: VanRiperMktg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35309
title: Van Riper Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03323f'
    - '#424e5b'
    - '#847352'
    - '#7196a6'
    - '#ced7df'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
